### ISSUE TITLE
DB query optimization suggestion

### ISSUE THREAD

**Issue by aniliyidogan** [egemen-dev/mobility_uniqueness#1]
In cases where there are multiple language and translation fields in a table, I would like to suggest a way to reduce the number of queries. I haven't used this library, so I'm not entirely certain about this solution. However, I thought this approach could reduce the query count and improve performance.

```ruby
query_classes = args.group_by { |attr| self.mobility_query_class(attr) }
query_classes.each do |query_class, attributes|
  values = self.current_locales.map do |locale|
    attributes.map { |attr| send(:"#{attr}_#{locale}")}
  end.flatten

  count_by_group = query_class
    .where(locale: self.current_locales)
    .where(translatable_type: self.class.to_s)
    .where(key: attributes, value: values)
    .where.not(translatable_id: id)
    .group(:key, :locale, :value)
    .count

  count_by_group.each do |(key, locale, _value), count|
    self.errors.add(:"#{key}_#{locale}", message) unless count.zero?
  end
end 
```

**Comment by egemen-dev** [comment]
Hi @aniliyidogan. Thanks for the suggestion! Batching the queries using `group` is a great idea. I've tested your approach, and it works as expected.

I ran a benchmark with 10k records but didn’t notice a significant difference, though my development environment might not be ideal for this. However I think your suggestion will improve the performance anyways, because it performs a single query for each query_class with the locales and attribute values put together

Would you be interested in opening a PR for your suggestion after I merge the [add test case](https://github.com/egemen-dev/mobility_uniqueness/pull/2) branch? I’m currently in the process of adding test cases to the gem.
